# Assignment 2

Deadline: 26.03.2025, 12:00 CET

<Add your name, student-id and emal address>

## 1. Linearization of Turnover

**(15 points)**

Turnover constraints are used to limit the amount of change in portfolio weights between periods, helping to manage transaction costs and maintain portfolio stability.

Your task is to implement a method `linearize_turnover_constraint` for the class `QuadraticProgram`, which modifies the quadratic programming problem to incorporate a linearized turnover constraint. This will involve updating the objective function coefficients, equality and inequality constraints, as well as the lower and upper bounds of the problem. 

Additionally, complete the example provided below to demonstrate that your method functions correctly.

In class, we discussed a solution that involved augmenting the dimensionality by a factor of three. Here, you are asked to implement an alternative method that involves a two-fold increase in dimensions. If you are unable to implement the two-fold method, you may proceed with the three-fold approach.

### Function Parameters:
- `x_init` (np.ndarray): The initial portfolio weights.
- `to_budget` (float, optional): The maximum allowable turnover. Defaults to `float('inf')`.

### Steps for Function Implementation:

As discussed in the lecture, introduce auxiliary variables and augment the matrices/vectors used for optimization.

- **Objective Function Coefficients**:  
  Pad the existing objective function coefficients (`P` and `q`) to accommodate the new variables introduced by the turnover constraint.  
  *Note*: "Padding" refers to adding extra elements (typically zeros) to an array or matrix to increase its size to a desired shape.

- **Equality Constraints**:  
  Pad the existing equality constraint matrix (`A`) to account for the new variables.

- **Inequality Constraints**:  
  Pad the existing inequality constraint matrix ('G') and vector ('h') and further add a new inequality constraint row to incorporate the turnover constraint.  

- **Lower and Upper Bounds**:  
  Pad the existing lower (`lb`) and upper (`ub`) bounds to accommodate the new variables.

- **Update Problem Data**:  
  Overwrite the original problem data in the `QuadraticProgram` class with the updated matrices and vectors to include the linearized turnover constraint.

In [107]:
# Import standard libraries
import types
import os
import sys

# Import third-party libraries
import numpy as np
import pandas as pd

# Import local modules
project_root = os.path.dirname(os.path.dirname(os.getcwd()))   # Change this path if needed
src_path = os.path.join(project_root, 'qpmwp-course', 'src')
sys.path.append(project_root)
sys.path.append(src_path)
from estimation.covariance import Covariance
from estimation.expected_return import ExpectedReturn
from optimization.constraints import Constraints
from optimization.quadratic_program import QuadraticProgram
from helper_functions import load_data_msci

In [108]:
def linearize_turnover_constraint(self, x_init: np.ndarray, to_budget=float('inf')) -> None:
        '''
        Linearize the turnover constraint in the quadratic programming problem.

        This method modifies the quadratic programming problem to include a linearized turnover constraint.

        Parameters:
        -----------
        x_init : np.ndarray
            The initial portfolio weights.
        to_budget : float, optional
            The maximum allowable turnover. Defaults to float('inf').

        Notes:
        ------
        - The method updates the problem's objective function coefficients, inequality constraints,
        equality constraints, and bounds to account for the turnover constraint.
        - The original problem data is overridden with the updated matrices and vectors.

        Examples:
        ---------
        >>> qp = QuadraticProgram(P, q, G, h, A, b, lb, ub, solver='cvxopt')
        >>> qp.linearize_turnover_constraint(x_init=np.array([0.1, 0.2, 0.3]), to_budget=0.05)
        '''
        # Dimensions
        n = len(self.problem_data.get('q'))
        m = 0 if self.problem_data.get('G') is None else self.problem_data.get('G').shape[0] #how many inequality constraints are there originally

        # Update the coefficients of the objective function
        P_orig = self.problem_data.get('P')
        q_orig = self.problem_data.get('q')

        P = np.block([
                [P_orig, np.zeros((n, 2*n))],
                [np.zeros((2*n, 3*n))]
        ])
        q = np.concatenate([q_orig, np.zeros(2*n)])

        # Update the equality constraints Ax = b, b does not need change as it is still value 1 array
        A_orig = self.problem_data.get('A')

        A = np.hstack([A_orig, np.zeros((1, 2*n))])

        # Update the inequality constraints
        G_orig = self.problem_data.get('G') #size mxn
        h_orig = self.problem_data.get('h') # (m x 1)

       # Convert G_orig to 2D if needed
        if G_orig is not None:
            if G_orig.ndim == 1:
                G_orig = G_orig.reshape(1, -1)  # Make it 2D (1 x n)
            m = G_orig.shape[0]
        else:
            m = 0
            G_orig = np.zeros((0, n))  # Empty 2D array for vstack later

        # Now safely hstack
        G_extended = np.hstack([
            G_orig,                # (m x n)
            np.zeros((m, 2*n))      # (m x 2n)
        ])                         # Result: (m x 3n)

        # Turnover budget constraint
        G_sum = np.hstack([
            np.zeros((1, n)),      # (1 x n)
            np.ones((1, 2*n))      # (1 x 2n)
        ])                         # Result: (1 x 3n)

        h_budget = np.array([to_budget])

        #Turnover constraint
        identity = np.eye(n)
        G_turnover = np.vstack([
            np.hstack([identity, -identity, identity]),
            np.hstack([-identity, identity, -identity])
        ])
        h_turnover = np.hstack([
            x_init, -x_init
        ])

        # Combine constraints

        G = np.vstack([G_extended, G_turnover, G_sum])
        h = np.hstack([
            h_orig if h_orig is not None else np.zeros(0), 
            h_turnover,
            h_budget
        ]) 


        # Update lower and upper bounds
        lb_orig = self.problem_data.get('lb')
        ub_orig = self.problem_data.get('ub')

        lb = np.hstack([lb_orig, np.zeros(2*n)])
        ub = np.hstack([ub_orig, np.ones(2*n)])

        # Override the original matrices (notice: b does not change)
        self.update_problem_data({
            'P': P,
            'q': q,
            'G': G,
            'h': h,
            'A': A,
            'lb': lb,
            'ub': ub
        })

        return None

## Demo

#### Create P and q

In [109]:
# Load the msci country index data
N = 10
data = load_data_msci(path = '../data/', n = N)
X = data['return_series']

# Compute the vector of expected returns (mean returns)
q = ExpectedReturn(method='geometric').estimate(X=X, inplace=False)

# Compute the covariance matrix
P = Covariance(method='pearson').estimate(X=X, inplace=False)

q, P

(AT    0.000130
 AU    0.000288
 BE    0.000047
 CA    0.000269
 CH    0.000149
 DE    0.000151
 DK    0.000429
 ES    0.000128
 FI    0.000145
 FR    0.000199
 dtype: float64,
           AT        AU        BE        CA        CH        DE        DK  \
 AT  0.000239  0.000054  0.000125  0.000075  0.000097  0.000138  0.000097   
 AU  0.000054  0.000104  0.000039  0.000030  0.000035  0.000041  0.000041   
 BE  0.000125  0.000039  0.000175  0.000064  0.000104  0.000137  0.000093   
 CA  0.000075  0.000030  0.000064  0.000130  0.000058  0.000087  0.000053   
 CH  0.000097  0.000035  0.000104  0.000058  0.000120  0.000121  0.000086   
 DE  0.000138  0.000041  0.000137  0.000087  0.000121  0.000202  0.000105   
 DK  0.000097  0.000041  0.000093  0.000053  0.000086  0.000105  0.000151   
 ES  0.000150  0.000044  0.000138  0.000081  0.000116  0.000164  0.000100   
 FI  0.000140  0.000050  0.000136  0.000091  0.000126  0.000180  0.000119   
 FR  0.000143  0.000045  0.000142  0.000084  0.000122

### Create some constraints, instantiate an object of class QuadraticProgram, and add the method linearize_turnover_constraint to the instance.

In [110]:
# Instantiate the constraints with only the budget and long-only constraints
constraints = Constraints(ids = X.columns.tolist())
constraints.add_budget(rhs=1, sense='=')
constraints.add_box(lower=0.0, upper=1.0)
GhAb = constraints.to_GhAb()

# Create a quadratic program and linearize the turnover constraint
qp = QuadraticProgram(
    P = P.to_numpy(),
    q = q.to_numpy() * 0,
    G = GhAb['G'],
    h = GhAb['h'],
    A = GhAb['A'],
    b = GhAb['b'],
    lb = constraints.box['lower'].to_numpy(),
    ub = constraints.box['upper'].to_numpy(),
    solver = 'cvxopt',
)

# Add the linearized turnover constraint method to the instance of class QuadraticProgram
qp.linearize_turnover_constraint = types.MethodType(linearize_turnover_constraint, qp)

constraints.to_GhAb()

{'G': None,
 'h': None,
 'A': array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 'b': array(1.)}

### Add a turnover limit of 50%. Solve the problem and check whether the turnover constraint is respected.

In [111]:
# Prepare initial weights
x_init = pd.Series([1/X.shape[1]]*X.shape[1], index=X.columns)

# Add the linearized turnover constraint
qp.linearize_turnover_constraint(x_init=x_init, to_budget=0.5)

# Solve the problem
qp.solve()

# Check the turnover
solution = qp.results.get('solution')
ids = constraints.ids
weights = pd.Series(solution.x[:len(ids)], index=ids)

print("Turnover:")
print(np.abs(weights - x_init).sum())

Turnover:
0.4979075776642612


In [112]:
n = 3  # Example with 3 assets
G_orig = np.array([[1, 0, 0], [0, 1, 0]])  # Example original constraints
m = G_orig.shape[0]

G = np.block([
    [G_orig, np.zeros((m, 2*n))],
    [np.zeros((1, n)), np.ones((1, 2*n))]
])

G_mysol = np.block([
                [G_orig, np.zeros((m, 2*n))],
                [np.zeros((1, n)), np.ones((1, 2*n))]
        ])

print(G_orig, G_mysol)  # Should be (3, 9)

[[1 0 0]
 [0 1 0]] [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1.]]
